import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <header style={{backgroundColor:'lightblue', padding:'1rem'}}>
        <div className="flex items-center justify-center mt-2 relative">
                    <img
                        src='/nextjsimg.png'
                        alt="screenshot of nextjs!!!"
                        width={100}
                        height={100}
                        className='absolute left-2 hidden md:block'
                    />
                    <div className='text-center'>Welcome to NextJs App!!!</div>
                </div>
          
        </header>

        
        <div style={{ display: 'flex', height: '100%' }}>
                <div style={{ width: '20%', padding: '10px', height: '100%' }}>
                    <Sidebar />
                </div>

                <div style={{ width: '80%', backgroundColor: '#fff', padding: '10px', height: '100%' }}>
                {children}
                </div>
            </div>

        <footer style={{backgroundColor:'ghostwhite', padding:'1rem'}}>
            <p>Footer</p>
        </footer>
      </body>
    
    </html>
  );
}
